### ISSUE TITLE
missing types

### ISSUE THREAD

**Issue by RienduPre** [jvmahon/homebridge-homeseer#10]
Too bad accessories like alarm, thermostats, door etc. aren't supported anymore

This version looks promising, but because less HomeKit accessoires are supported it's not usable for me.
You stated that you needed those device type, but why don't you leave as they are working in the original plugin?

Thanks,
Rien

**Comment by jvmahon** [comment]
I'm working on adding some back in, but need some additional information to do that. Its really an entirely different polling / updating architecture than the original plugin so the work in that older plugin isn't transferrable.

I am open to adding additional accessories. However, in the meantime, another option is to take the "original" plugin and use it alongside this one for those devices. To do that, you would have to make a copy of the original plugin and then modify its Platform name. I think this would require changes to lines 52, 53 and 241 of the original plugin's index.js file to rename it as a different plugin (maybe changing "HomeSeer to something like "HomeSeerOriginal". In your config.json file, you would then just set up devices that I don't support in a separate platform section.

The next item I plan to add is Garage Door Opener as I think I have an understanding of how this works.
As for alarm, door, thermostat - can you specify the manufacturer / model of the device you would like to use? I'll take a look. I'd also need youto send me a screen shot of the HomeSeer web page showing the device grouping that HomeSeer sets up for each device in the group as well as the Status tab for each device showing the control and status values used by HomeSeer.

**Comment by jvmahon** [comment]
See Wiki entry: https://github.com/jvmahon/homebridge-homeseer/wiki/Using-'original'-and-'new'-Plugin-in-Parallel

These instructions explain how to use old plugin in parallel with this updated one. You can then use the old plugin for your alarm, thermostat, etc., while using the new plugin for lights, sensors, locks and other devices that are implemented.

**Comment by RienduPre** [comment]
Hi,

I have a Caddx alarm, see the configuration in my current config.json
` {
            "armNightValue": "3",
            "ref": 600,
            "armedStayValues": "[3]",
            "disarmedValues": "[1]",
            "armedNightValues": "[3]",
            "armedAwayValues": "[2]",
            "alarmValues": "[4,5]",
            "disarmValue": "1",
            "type": "SecuritySystem",
            "armAwayValue": "2",
            "name": "Caddx Alarm"`
So just one HS ref with several values for each state, this results, see screenshots

<img width="999" alt="2018-02-28_1855" src="https://user-images.githubusercontent.com/9009949/36803864-252747fc-1cb9-11e8-80f9-54a7cefdd104.png">
<img width="1000" alt="2018-02-28_1854" src="https://user-images.githubusercontent.com/9009949/36803866-2545ead6-1cb9-11e8-8d52-17425a058fa0.png">

**Comment by jvmahon** [comment]
Thanks.
At the moment, I"m only adding Z-Wave devices to my plugin's code. I could try to help you a bit more but as this is only a hobby, I can only get to it when work permits (at that point, that is likely several weeks or more ). However, as noted above, I've implemented a work around for you to allow you to use the 'old' plugin along with mine. I think that works to allow you to use your alarm as you previously could, but also take advantage of the features I've put in my update for Z-wave devices. Does that work for you?
