### ISSUE TITLE
Feature request - Security System

### ISSUE THREAD

**Issue by AlanSmithe** [jvmahon/homebridge-homeseer#15]
I've created a virtual device in HomeSeer that I use for my security system. It would be nice if I could control it with homebridge. 

The plugin of jrhubott had to following 
`
{
"ref":230,                      // Required - HomeSeer Device Reference of a Security System

"type":"SecuritySystem",        // Required for a security system

"name":"Home alarm",            // Optional - HomeSeer device name is the default

"armedStayValues":[0],          // Optional - List of the HomeSeer device values for a HomeKit security 
state=ARMED-STAY

"armedAwayValues":[1],          // Optional - List of the HomeSeer device values for a HomeKit security state=ARMED-AWAY

"armedNightValues":[2],         // Optional - List of the HomeSeer device values for a HomeKit security state=ARMED-NIGHT

"disarmedValues":[3],           // Optional - List of the HomeSeer device values for a HomeKit security state=DISARMED

"alarmValues":[4],              // Optional - List of the HomeSeer device values for a HomeKit security state=ALARM

"armStayValue":0,               // Required - HomeSeer device control value to arm in stay mode. If you don't have this mode, select any value that arms your system

"armAwayValue":1,               // Required - HomeSeer device control value to arm in away mode. If you don't have this mode, select any value that arms your system

"armNightValue":2,              // Required - HomeSeer device control value to arm in night mode. If you don't have this mode, select any value that arms your system

"disarmValue":3                 // Required - HomeSeer device control value to disarm security system
}
`
Where value 4 is 'alarm has been triggered'

Could you implement this in your plugin?

**Comment by jvmahon** [comment]
for your security system  there is a wiki entry explaining how to use the old plugin alongside the new one. I suggest you get that eight try that for now.

**Comment by AlanSmithe** [comment]
Ah I found [it](https://github.com/jvmahon/homebridge-homeseer/wiki/Using-'original'-and-'new'-Plugin-in-Parallel) I'll try that for now.

Would be nice though to have the real time status updates ;)

**Comment by jvmahon** [comment]
FYI - the SecuritySystem type is now supported.
To update to the new version, just do a:

     npm -g update

**Comment by AlanSmithe** [comment]
Haha nice, I was secretly hoping that RienduPre comment would spark interest in integrating the security system in your plugin ;) I'll try it out immediately

**Comment by jvmahon** [comment]
OK. I'm closing this comment for now. Re-open if you have an issue.

**Comment by AlanSmithe** [comment]
Not really an issue but I can't find the config

In the Read Me it states
_See sample configuration files in 'config' directory, and wiki pages for configuraiton parameter setings._

In the config folder it says
_{"type":"SecuritySystem",	... see Readme and wiki documents for parameter settings },_

And I can't find the related wiki.

**Comment by jvmahon** [comment]
Hi Alan,
You can't find the wiki because I haven't written it yet! I'm about a day away from doing that, but I published the 2.3.6 release because I had introduced a serious bug into 2.3.5 so I wanted to rush 2..3.6 out.

The configuration parameters for SecuritySystem are the same as was in the old jrhubott plugin so you can use that as a guide..

**Comment by RienduPre** [comment]
This is cool !!!
