### ISSUE TITLE
Request for custom devices

### ISSUE THREAD

**Issue by RienduPre** [jvmahon/homebridge-homeseer#29]
Let me first tell you that you did a great job with this plugin and the feature request handling. I now have al my devices running in your version.

What I was wondering is, if it's possible to add custom accessories or characteristics which are used by Elgato for instance. Information like Power consumptions (see 
![fullsizeoutput_1818e](https://user-images.githubusercontent.com/9009949/37646548-42bd7dba-2c2a-11e8-8f35-07d28a1c6688.jpeg)
picture) 

Thanks,
Rien

**Comment by jvmahon** [comment]
Unfortunately, at this time, I just don't have the time or knowledge to do it, particularly for something that isn't well documented. At the moment, I'm still working to get the non-custom characteristics fully implemented and bug-free. After that, I'm afraid I'll have to turn back to my "real" job!
