### ISSUE TITLE
Help Improve This - Device Mappings

### ISSUE THREAD

**Issue by jvmahon** [jvmahon/homebridge-homeseer#3]
I'm like to add an additional feature the plugin so that user's don't have to specify the device type in the config.json file. Instead, the plugin would get the type information directly from HomeSeer. The approach I'm taking is to use the "Device Type (String)" field from the device's Advanced tab in in HomeSeer and map these types to the HomeKit types that are not specified in the plugin's config.json file.  However, I don't have all of the device type strings so I can't figure out all of the mappings. If any of you can add to the types by checking your HomeSeer values and replying to this issue with additonal device type strings, that would be appreciated. List of what's needed is below. If you have equivalent strings for HomeSeer non-Zwave devices (e.g., Zigbee, etc) , please feel free to provide those and I'll include them too.

** Note that I realize the "Device Type (String)" field in Homeseer can be changed by the user, so this only works if the user doesn't manipulate the string. A better approach may be to use the device type / subtype enumerated values returned from HomeSeer during a status poll, but those don't seem to be documented anywhere, so using the "Device Type (String)"  may be the best I can do on this feature.

Here are the mappings that I do have:
  - "Z-Wave Switch Binary"        ->  "Switch"
  - "Z-Wave Switch Multilevel"    ->  "Lightbulb" 
  - "Z-Wave Door Lock"            ->  "Lock"
  - "Z-Wave Temperature"          ->  "TemperatureSensor"
  - "Z-Wave Water Leak Alarm"     ->  "LeakSensor"

What I'm missing:
Fan, 
Outlet, 
MotionSensor, 
CarbonMonoxideSensor, 
CarbonDioxideSensor, 
ContactSensor, 
OccupancySensor, 
SmokeSensor, 
LightSensor, 
HumiditySensor

**Comment by knaackville** [comment]
Here are some from my setup, which appear to repeat some of the mappings noted in your post:

Fan (GE Zwave fan controller) - "Z-Wave Switch Multilevel" 
Lutron Caseta Wall Dimmer (using associated plugin for Homeseer) - "Lamp Module"
Lutron Caseta Wall Switch (using plugin) - "Appliance Module"
Outlet - "Z-Wave Switch Binary"

**Comment by AlanSmithe** [comment]
This is from the Fibaro Univeral Sensor and an Aeon Lab door sensor

Z-Wave Sensor Binary
0 	Off-Closed-No Motion
255 On-Open-Motion

Z-Wave General Purpose Alarm
0	OK
255	ALARM

**Comment by AlanSmithe** [comment]
I have a qubino 10v dimmer that I use for my ventilation.
The device string is Z-Wave Switch Multilevel. Would it be possible to manually create a Fan?

**Comment by jvmahon** [comment]
You should already be able to do this using the “Fan” type.

 

E.g., in your config.json “Accessories” group you would have an entry like …

 

{  “type”:”Fan”, “name”:”Living Room”,  "ref":235, “can_dim”:”true”        },

 

As a practical matter, the “Type” works almost exactly the same as the “LightBulb” type - i.e., its just like a dimmer. The only difference is that in the iOS Home app, it shows a picture of a rotating fan instead of a bulb.
