### ISSUE TITLE
Window covering issue

### ISSUE THREAD

**Issue by RienduPre** [jvmahon/homebridge-homeseer#31]
Hi,

Is use these values in the config.json

`  "ref": 815,
            "type": "WindowCovering",
            "binarySwitch":true,
            "openValue": 0, 
            "closedValue": 255, 
            "name": "Rolluik status"`

But the status on my HomeKit app is still wrong, It sends the right value I guess but the status of the accesoire is incorrect.

See attached images if that helps

<img width="626" alt="2018-03-23_1227" src="https://user-images.githubusercontent.com/9009949/37836815-ca6283b0-2eb3-11e8-837f-6ff7da25e9b4.png">
<img width="517" alt="2018-03-23_1225" src="https://user-images.githubusercontent.com/9009949/37836816-ca7fac92-2eb3-11e8-92d6-c3b264f93f65.png">
<img width="539" alt="2018-03-23_1215" src="https://user-images.githubusercontent.com/9009949/37836817-caa8edd2-2eb3-11e8-9e79-c9a51c047d4b.png">

**Comment by jvmahon** [comment]
You’re right. There’s a bug. I have a fix for it which I’ll publish in version 2.3.9.  Possibly today, but I'm traveling for work now, so it may not happen until Sunday. I'll close this comment once I publish the fix in a new update.

**Comment by RienduPre** [comment]
Thanks again

**Comment by jvmahon** [comment]
This should now be working. Re-open the issue if there is still a problem.

Use:

    npm -g update

To update to version 2.3.10

**Comment by RienduPre** [comment]
It's solved, thanks....
