### ISSUE TITLE
Please add a offValue parameter for switches

### ISSUE THREAD

**Issue by jrhubott** [jvmahon/homebridge-homeseer#36]
This would allow for more configuration and would allow me to replace my extension with yours - which is much better.

Thanks

**Comment by jvmahon** [comment]
I have a test version you can try. You can install it using:

      npm -g install git://github.com/jvmahon/homebridge-homeseer#offValues

I will also be testing it. Assuming I find no issues, I'll publish it in a few days. Look for a release greater than the current 2.3.11.

**Comment by jvmahon** [comment]
FYI - I noticed a small issue relating to battery handling and the setting of default thresholds that I want to fix before I publish the new release, so it may be Saturday or Sunday before I publish 2.3.12.

**Comment by jvmahon** [comment]
Done.
You can return to using the 'published' version by executing

     npm -g install homebridge-homeseer-plugin-2018

Note the new version much more carefully checks the config.json file for inconsistencies or for incorrect parameter usage, so you may have to correct your config.json on the first run.
