### ISSUE TITLE
Include the homeseer room name when using the lights array

### ISSUE THREAD

**Issue by jrhubott** [jvmahon/homebridge-homeseer#37]
When adding a lot of lights using the lights array it is hard to identify the lights.  If you could create the device name including the room name it would help.

Thanks

**Comment by jvmahon** [comment]
How about something like the HomeSeer room name followed by a period then the HomeSeer device name, so lights named "Floods" in the room "Kitchen" would be given the HomeKit name "Kitchen.Floods"

**Comment by jvmahon** [comment]
Done.
You can return to using the 'published' version by executing

     npm -g install homebridge-homeseer-plugin-2018

Note the new version much more carefully checks the config.json file for inconsistencies or for incorrect parameter usage, so you may have to correct your config.json on the first run.
