### ISSUE TITLE
Homebridge working - missing step to install Homeseer plugin??

### ISSUE THREAD

**Issue by TURSTY** [jvmahon/homebridge-homeseer#40]
Hi there. I have followed your instructions to install Homebridge on a Win 10 machine and its all working as it should (great instructions by the way). 
But I cant seem to see any instructions on how to correctly install the Homeseer plugin. I have tried the npm i homebridge-homeseer-plugin-2018 command in a admin CMD window, but its getting nothing but errors and when starting Homebridge after this, its saying no plugins found. Is there a missing step in the wiki? ie. a file that needs to be downloaded first or something? I see in the old plugin links it references downloading a zip file first, but nothing for the 2018 plugin. 

Any help would be much appreciated.

**Comment by jvmahon** [comment]
You are correct - the step was missing from the Wiki. I've now fixed that.  All you should need to do is to enter the following from a Windows command prompt:

     npm -g install homebridge-homeseer-plugin-2018

Let me know if this works for you.
