### ISSUE TITLE
Default name suggestion

### ISSUE THREAD

**Issue by rrman** [jvmahon/homebridge-homeseer#44]
By default, if the name of an accessory in config.json is not provided, it will default to "room name.device name" (with a dot in between). I've found a good naming convention to use, for my purposes at least, is "room name device name" (with a space in between). With this convention, the iOS Home App knows that "room name" is redundant, so the accessory's icon in the Home app just shows "room name device name." If I use the default provided by the plugin ("room name.device name", with a dot in between), then the Home icon shows "room name room name.device name", so that "room name" shows up twice. 

Hence, just a suggestion that a good default for name, if not provided, would be "room name device name" (with a space). For me, though, since json doesn't allow comments, I still like to explicitly fill in the name for each accessory so I can easily tell what it's for. But other users might like not to have to enter the name in config.json. Anyway, just a suggestion

Also, just wanted to reiterate: what a great plugin this is! Very stable, very good performance. Thanks!

**Comment by jvmahon** [comment]
I was not aware of that behavior by the iOS Home App. Thanks for letting me know. I will change the "." to a space in an updated release. I'll leave this comment open until I do so.

**Comment by darrenmcuk** [comment]
nice one...look forward to the update...

**Comment by goldriver2** [comment]
Could the naming convention be a parameter in the config.json file ? , for me I would like to only have Device Name (refering to Homeseer "Voice Command" parameter in the homeseer devices) sent to Homekit.

Now, once I start Homekit, I have to go and manually modify all device names because they appear "Room.Device Name"
