### ISSUE TITLE
config needs uuid_base

### ISSUE THREAD

**Issue by AlanSmithe** [jvmahon/homebridge-homeseer#5]
Hi Jim,

I noticed when I added more devices that I got the following error:

`
Feb 20 13:07:50 Homebridge homebridge[4246]: /usr/lib/node_modules/homebridge-homeseer-plugin-2018/lib/HomeSeerUtilities.js:113
Feb 20 13:07:50 Homebridge homebridge[4246]: #011#011#011#011throw new SyntaxError(error);
Feb 20 13:07:50 Homebridge homebridge[4246]:           ^
Feb 20 13:07:50 Homebridge homebridge[4246]: SyntaxError: config.json error for device name: Kitchen Device base_uuid already used for base_uuid: undefined
`

My config looked like this:

`
{
            "platform": "HomeSeer",
            "host": "http://aperture.city17.nl",
            "poll": 60,

            "accessories": [
                {
                    "ref": 297,
                    "name": "Hall",
                    "type": "Switch"
                },
                {
                    "ref": 322,
                    "name": "Kitchen",
                    "type": "Lightbulb"
                }
}
`

When I changed it to 

`
{
            "platform": "HomeSeer",
            "host": "http://aperture.city17.nl",
            "poll": 60,

            "accessories": [
                {
                    "ref": 297,
                    "name": "Hal",
                    "type": "Switch",
                    "uuid_base":"297"
                },
                {
                    "ref": 322,
                    "name": "Keuken",
                    "type": "Lightbulb",
                    "uuid_base":"322"
                }
}
`

The plugin works

**Comment by jvmahon** [comment]
Thanks for letting me know. Both of your configs should work. Would you mind responding to this by attaching your entire config.json file (both working and non-working versions if you can). The latest code has some configuration checking included to make sure you don't use the same uuid_base more than once - obviously that's failing and it would be helpful to have your config.json so I can trace the error. I'll then check the code tonight (in about 12 hours or so) and see if I can fix it.

**Comment by jvmahon** [comment]
Never mind - you don't need to send the config. I found the error and will fix it this evening.

**Comment by jvmahon** [comment]
I now have a fix which I'm ready to push to npm. However, you also raised a question by email regarding the "Fan" type - is that not working for you? Let me know - if there is a problem there I'll try to fix that too and get it into one update.

**Comment by AlanSmithe** [comment]
Hi Jim,

No there isn’t a problem. 
I forgot the can_dim flag, I figured it out a little bit later that’s why I deleted the comment.
Looking forward to your next update.

Eric

**Comment by jvmahon** [comment]
FYI - I have a new development version ready for testing. If you are willing to be a tester, see the Wiki page at: 

https://github.com/jvmahon/homebridge-homeseer/wiki

 

This new version adds an “instant” device update feature which uses the ASCII interface of HomeSeer to get instant device change reports so you no longer have to wait for the next poll cycle to see when a device has updated. This should be particularly useful for devices such as contact sensors and alarm sensors where you don’t want to wait for a poll to see the change. Another advantage is that dimmable devices will now turn on to their last-value  (assuming the last-value feature is supported by your Z-Wave dimmer - I think most do support the feature).

 

If the connection to the HomeSeer ASCII interface is successful, the plugin will then reduce its polling to once every 60 seconds. Its probably possible to completely turn off polling, but I’ve leaf it on at a reduced rate just to make sure HomeKit / HomeSeer stay synchronized.

 

If you are able to test the development version out, please let me know if it installed properly and if you noted any device issues.

 

If you don’t have time to be a tester, I’ll likely roll these changes into the “main” release sometime next week.

 

Regards,

Jim
