### ISSUE TITLE
[HomeSeer] Cannot read property 'obstructionClearValues' of undefined

### ISSUE THREAD

**Issue by amattas** [jvmahon/homebridge-homeseer#50]
Unable to include garage door opener in HomeBridge. This is the snipped from Config.Json

                                {
                                        "ref":316,
                                        "type":"GarageDoorOpener",
                                        "name":"Garage Big Door",
                                        "obstructionRef": 317
                                }

During startup it seems to be properly adding the value.

Jun 23 16:15:29 jarvis homebridge[10382]: [6/23/2018, 4:15:29 PM] [HomeSeer] Config.json property information updated from: {"ref":316,"type":"GarageDoorOpener","name":"Garage Big Door","obstructionRef":317} to: {"ref":316,"type":"GarageDoorOpener","name":"Garage Big Door","obstructionRef":317,"uuid_base":"Ref316","obstructionClearValues":[0,74],"openValue":255,"closedValue":0,"openingValue":254,"closingValue":252,"stoppedValue":253}

**Comment by jvmahon** [comment]
I haven't heard of this problem before but will try to help. Can you provide some more information.
1. What kind of garage door opener is it?
2. From your subject line, it looks like you are getting the error "Cannot read property 'obstructionClearValues' of undefined" - can you post the rest of the error message - specifically, the part telling the file and line numbers where the error was generated.

Also, maybe try adding the garage door opener, but leave out the "obstructionRef"

**Comment by amattas** [comment]
It's a Linear Z-Wave Plus opener (I have two of them). Unfortunately that's all of the message I've received. I tried doing some debugging and this is how far I have gotten, I don't know enough about HAP and HomeBridge yet to figure out where to look next. 


`		case( characteristicObject.UUID == Characteristic.ObstructionDetected.UUID ):
			{
				newValue = getHSValue(characteristicObject.HSRef);
				**//characteristicObject.config is undefined here for some reason.**
				if (characteristicObject.config.obstructionClearValues.includes(newValue))
				{
					characteristicObject.updateValue(0);// No Event Value
				}
				else
				{
					characteristicObject.updateValue(1);  // Anything else, consider it obstructed.
				}
				break;
			}
`

I'm running in HomeBridge API version 2.2, and I have the openers working in the older homebridge-homeseer plugin, but it seems like there's been some nice improvements in this version.

**Comment by amattas** [comment]
I think I created the issue and created a pull request. See PR #51

**Comment by amattas** [comment]
Sorry see PR #52

**Comment by jvmahon** [comment]
I've merged your PR and will push a new version to npm so I'm closing this comment. Thanks for the help in finding the bug!
