### ISSUE TITLE
Z-Wave Thermostat looping problem

### ISSUE THREAD

**Issue by TURSTY** [jvmahon/homebridge-homeseer#53]
Hey there, I have had an issue with a Z-wave thermostat that gets itself into a never ending loop if its turned on then off too quickly. Say for example I turn the heat pump on with its remote during the day. If I then want to turn it off with the Home app (which still thinks its off because it doesn't update when turned on with the remote), you have to set the mode to something other then off, then back to off to send the command. Today my Partner did this fairly quickly, and the app got itself into a never ending look on and off.

On the home app its in a never ending Off>Heat>Off>Heat>Off>Heat>etc, about 10 times a second. Below is the log from HomeSeer that shows the device control command coming from Homebridge, but it looks like the Control command and status are 1 command out of sync. Not sure if this is relevant or not, but its an observation. It will continue this, with the heat pump beeping its head off until the Homebridge app is forced closed and restarted.

Is this a bug, or a limitation of the time delay with Zwave commands being sent and received?

[Error log.txt](https://github.com/jvmahon/homebridge-homeseer/files/2174902/Error.log.txt)

**Comment by jvmahon** [comment]
Hi Tursty. So, obviously, it shouldn't do this. Unfortunately, I don't have a Z-wave thermostat and may not be able to effectively debug this, but does it "normally" work - i.e.,  is this just a race condition that occasionally happens, or is this something that you can consistently repeat?  What type of thermostat is it? Can you send me a screen shot showing all of the devices in HomeSeer that are created for this thermostat (along with their reference #s) and the line from your config.json file setting up this thermostat.

**Comment by jvmahon** [comment]
I haven' seen a further response, so I'm closing this comment.
