### ISSUE TITLE
Cant get "old platform" to work

### ISSUE THREAD

**Issue by mbaastrup** [jvmahon/homebridge-homeseer#56]
First of all I really like the new 2018 version w. instant update, and higher speed.
I have a few devices that isn't supported (e.g. window controls), hence I am trying to get the "old platform" support to work as described here:https://github.com/jvmahon/homebridge-homeseer/wiki/Using-'original'-and-'new'-Plugin-in-Parallel

With my config.json clean for 2018 everything is running well. When adding the configuration for old platform I get: 
[2018-8-29 20:08:50] Loaded config.json with 0 accessories and 2 platforms.
[2018-8-29 20:08:50] ---
[2018-8-29 20:08:50] Loaded plugin: homebridge-homeseer-jrhubott
homebridge API version: 2.2
[2018-8-29 20:08:50] Registering platform 'homebridge-HomeSeerPlatform.HomeSeerOriginal'
[2018-8-29 20:08:50] ---
[2018-8-29 20:08:50] Loaded plugin: homebridge-homeseer-plugin-2018
homebridge API version: 2.2
[2018-8-29 20:08:50] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
[2018-8-29 20:08:50] ---
[2018-8-29 20:08:50] Loading 2 platforms...
[2018-8-29 20:08:50] [HomeSeer] Initializing HomeSeer platform...
[2018-8-29 20:08:50] [HomeSeer] System default periodic polling rate set to: 10 seconds
/usr/lib/node_modules/homebridge/lib/api.js:122
     throw new Error("The requested platform '"

+ name + "' was not registered by any plugin.");
     ^

Error: The requested platform 'HomeSeerOrignal' was not registered by any plugin.
   at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
   at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:315:45)
   at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
   at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
   at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
   at Module._compile (module.js:652:30)
   at Object.Module._extensions..js (module.js:663:10)
   at Module.load (module.js:565:32)
   at tryModuleLoad (module.js:505:12)
   at Function.Module._load (module.js:497:3)

Regards, 
Martin 

I have done a few clean installs to see if I missed out on something, but cant seem to find the error.

**Comment by jvmahon** [comment]
Actually, after I wrote the original guide for using the two plugins together, I incorporated most of the "old" devices into the new plugin. Which specific "old" platform device type are you trying to use the 'old' plugin for? Maybe I can give you instructions on how to use it with the 'new' plugin instead of trying to fix the problem you're having.

**Comment by mbaastrup** [comment]
That makes sense and I believe its the right priority - I would rather get out of the old one. 
My windows are controlled by this: http://qubino.com/products/flush-shutter-dc/
They are in HomeSeer : Z-Wave Switch Multilevel Root Device with child devices, both a binary switch and a multilevel one (0-100%). I can make them as light bulps, but "Siri turn on the light" opens all my windows of course ;-)

**Comment by mbaastrup** [comment]
And I have a bunch of lumen and humidity sensors too, but I live without them

**Comment by jvmahon** [comment]
I think you are running into a documentation problem.

LightSensor and HumiditySensor are implemented but not well documented in the Wiki. 

Look here and you will find entries for these types and their parameters: https://github.com/jvmahon/homebridge-homeseer/wiki/Config.json-Settings 

There's also a "WindowCovering" type though, again, poorly documented.

I'll try to add something to the Wiki this weekend.

As for the WindowCovering, maybe I need to do something more for your Qubino device - can you explain, what is the "binary" switch used for and what is the "multilevel" switch used for?

**Comment by jvmahon** [comment]
As an FYI, Here's a more complete list of supported device types:

Switch
Outlet
TemperatureSensor
CarbonMonoxideSensor
CarbonDioxideSensor
ContactSensor
MotionSensor
LeakSensor
OccupancySensor
SmokeSensor
LightSensor
HumiditySensor
Lock
Fan
Lightbulb
GarageDoorOpener
WindowCovering
Thermostat
SecuritySystem
Valve

**Comment by mbaastrup** [comment]
I actually use the windowcovering service for my curtains, it works fine, simple up and down with a virtual device in HS. I will try out the lumen and humidity, they should work fine when the other sensor types does.

For the Qubino devices I used them on the old platform, just found some piece of the code in the HomeSeer.js: 

```
        case "Window": {
            var windowService = new Service.Window();
            windowService
                .getCharacteristic(Characteristic.CurrentPosition)
                .on('get', this.getValue.bind(this));
            windowService
                .getCharacteristic(Characteristic.TargetPosition)
                .on('set', this.setValue.bind(this));
            windowService
                .getCharacteristic(Characteristic.PositionState)
                .on('get', this.getPositionState.bind(this));
            if( this.config.obstructionRef ) {
                windowService
                    .addCharacteristic( Characteristic.ObstructionDetected )
                    .on('get', this.getObstructionDetected.bind(this));
            }
            services.push( windowService );
            break;

```

In the old platform I had them set up in config.json like:

{"ref":887,"type":"Window","name":"Window","uuid_base":"887_Window","CurrentPosition" : 887,"TargetPosition" : 887,"poll" : 20,"statusUpdateCount" : 10},

It cant be far from a garagedoor I guess? I never used the obstruction parameter and it was optional.

For the Qubino shutter the HS characteristics are:
The Multilevel child: Off=0; 1-98=% of full cycle from open to closed; 99=On; 100-255=Unknown
The Multilevel child: Off=0; 255=On 
Off and On is the "Control Use" setting in HS, but the label I have set as "Open" = 99
I never use the binary, only the multilevel so I can set the window to e.g. 25% open.

Let me know if I can do more to increase the probability of implementation :-)
And again - thanks for the re-written plugin, its very fast compared.

**Comment by jvmahon** [comment]
Try the following with your Qubino and let me know if it works (and, if not, what is happening, if anything):
{"type":"WindowCovering", 		"ref" 877, 	"binarySwitch":false	},

**Comment by mbaastrup** [comment]
Works perfect on the Multilevel control (0%-100%) I can set a window to e.g. 33% open, full update with the ASCII etc. Of course it shows as a Window Covering in HomeKit hence reacting to a "Siri, close the shades" :-) But the structure works all fine! Can you replicate it in the code using the Windows service instead of WindowCovering?

**Comment by jvmahon** [comment]
O.K., so maybe I never really understood what you were doing. I assumed all along that you were controlling some kind of window covering, but from your last comment, I realized you might actually be using this to control the window itself. Is that correct?  If so, yes, I think it would be easy to replicate it for controlling an actual window, but please confirm that is what the issue really is. Thanks.

And just curious, if this is for moving the window itself,  what kind of window are you controlling (double hung?  casement?). How is the motor coupled to the window? Is there some kind of motor made especially for this?

**Comment by mbaastrup** [comment]
Indeed it is the windows I control with this - I have four of them. Two are side hung and two top hung (I am not sure thats the real way of describing, but you can see both types here as example: https://windowsupplydirectltd.co.uk/product/upvc-window-vent-over-side-hung-right/) 

I use an actuator, one on each - I found these cheap one: https://www.aliexpress.com/item/SOVik-2-inch-50mm-Stroke-Micro-Linear-Actuator-12V-DC-In-line-Structure-Motor-Round-Tubular/32792514350.html
The attachment to the window is done with small stuff I found at the local hardware shop, like these: https://www.screwfix.com/c/security-ironmongery/angle-brackets/cat840260# and some bolt like these: https://www.amazon.co.uk/Washers-Setscrew-Threaded-Stainless-Delivery/dp/B00BE559X8
It can for sure be done prettier, but mine are hidden behind the top of curtains/rollers anyway. (Curtains I also control btw)
The 12v DC actuator motor has mechanic stop in both full in and full out (100 mm are the ones I use). The Qubino controller has a function in the z-wave settings for running a full close-open-close cycle to know the motor span, and after running that, it understands what e.g. 50% means. 

I think I ended up with a price like 80 euro per window all in all, and it has been running for a few years now on all four windows and is used every day. 

I dont know if I have explained it that well as I am not familiar with the english terms for these type of components, but I will be happy to send you a picture or a video of the installation on mail.

**Comment by jvmahon** [comment]
A new version has been published to npm with support for a "Window" type. Use "Window" instead of "WindowCovering" and it should work. If you have problems, let me know (I could do only limited testing because I don't have a similar device).  You should be able  to update the plugin using:

npm -g update

**Comment by mbaastrup** [comment]
I can confirm that it work as expected - thank you for the great plugin, the support and fast turn around!

**Comment by jvmahon** [comment]
You're welcome.
