### ISSUE TITLE
Homekit won't update device status

### ISSUE THREAD

**Issue by AlanSmithe** [jvmahon/homebridge-homeseer#6]
Whenever I turn a light on or off with the switch or in HomeSeer, Homekit doesn't update status.
Only when I switch rooms in Homekit or close the app the status get's updated.

This problem isn't with any with my Z-Wave Switch Multilevel devices, so I changed the string from 
' Z-Wave Switch Binary' to 'Z-Wave Switch Multilevel' 
This didn't solve the issue nor changing the device type from Switch to Lightbulb

**Comment by AlanSmithe** [comment]
Terrible sorry but the problem solved itself, I've tested this issue with 3 binary lights and all showed the same behaviour. 
The only thing I can think off is my iPad is the home hub and I disconnected it from my wireless network.

**Comment by jvmahon** [comment]
Very strange. No idea why this would happen. If the behavior repeats, let me know. If you are still using iPad has a hub and this happens again, can you let me know the iOS version.

**Comment by AlanSmithe** [comment]
Ok will do.
My iPhone and iPad are running iOS version 11.2.5 but I'll will update both to .6 this week.
