### ISSUE TITLE
Msbuild error

### ISSUE THREAD

**Issue by CeloyT** [jvmahon/homebridge-homeseer#62]
I got this error, but i already have visual studio and NET.framework. Can someone explain the last step, i did't understand it.

`MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Users\MyUser\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n\build\bin
ding.sln]`

**Comment by jvmahon** [comment]
I haven't seen this before. Were you able to fix this? Did this occur while you were following the Wiki instructions for installing homebridge / homebridge-homeseer (if not, please review those instructions and follow them first).

**Comment by jvmahon** [comment]
Closed due to no further response.
