### ISSUE TITLE
cannot read properyt 'findindex'

### ISSUE THREAD

**Issue by jezzaf** [jvmahon/homebridge-homeseer#65]
hi, 

i have just updated homebridge and homebridge-homeseer 2018 and im getting the following error when starting homebridge.

[HomeSeer] Cannot read property 'findIndex' of undefined

if i remove all my accessories for the config.json it load fine however even with 1 it produces this error. 

any help would be appreciated. 

[config.txt](https://github.com/jvmahon/homebridge-homeseer/files/2612002/config.txt)

thanks

**Comment by jvmahon** [comment]
As a starting point, try using the attached simplified config.json and let me know if it works. [config.json.zip](https://github.com/jvmahon/homebridge-homeseer/files/2612222/config.json.zip)

Z-Wave lightbulbs can be specified in shortcut fashion which I've done in the attached (I didn't include all your bulbs, but enough to test this).  If it doesn't work, send a bit more detail:  1) Type of system (linux, windows, etc.); 2) What version of node are you running? 3) Are you using the latest version of the plugin? 4) Can you send a screen capture of all the messages shown up until the "Cannot read 'findIndex' of undefined.

I also noticed that in your "host" configuration, you included the port "84".  I didn't do much testing with user-defined ports so there's a chance it has something to do with processing that. Can you reset your system to use the "default" port which is 80 and then only specify the IP in the config.json. I.e., set host to :           "host":"http://192.168.0.3",

If that works, I'll add some more of your devices back in and ask you to try again so we can pinpoint where it goes wrong. I'd like to see if we can both get your system going, but also figure out what made it fail so I can fix the code.

Maybe there is something wrong in the parsing of the onValue, offValue, can_dim, uses99Percent or some other parameter. As a rule, these parameters only exist in case you need to override the Z-Wave defaults, but in almost all cases, you've set them to the defaults so they don't serve much purpose. Try deleting them. Generally, in the "accessories" block, all you need to specify for a Z-Wave device is the "type" and the "ref" parameter. 

Also, there are a few cases where you specify "onValue":100 for a Switch. What type of Switch is this? If its Z-Wave, that is not a valid parameter setting. It could be that.

**Comment by jezzaf** [comment]
hi,

the config you sent over worked. 

i never specified them as you did as i had copied most of the file over form an older vision of homebridge. however it was running before i did a fresh in stall of everything. so im amusing i have the latest version of everything. 

the items with an on value of 100 are virtual devices in homeseer. these are probably the items i use the most.

thanks

**Comment by jezzaf** [comment]
i forgot to mention i did try a config with only 1 accessorize
[config2.txt](https://github.com/jvmahon/homebridge-homeseer/files/2612666/config2.txt)
 and that didn't work to see if it was the phrasing that had stuffed it up.

thanks

**Comment by jvmahon** [comment]
I tried your config with only one accessory and it seems to work. This is puzzling since I can't reproduce the error. Screen shots showing the screen messages before and up to the error would help.

I've attached an expanded config.json where I add in a few of your locks and other devices. Can you try using this file. If it works, expand it to include all of your lights, locks, motion sensors.

Also, can you try doing a 
npm -g update

to make sure you are on the latest version of all homebridge and plugin files.


[expanded config.zip](https://github.com/jvmahon/homebridge-homeseer/files/2612674/expanded.config.zip)

**Comment by jvmahon** [comment]
Can you do a backup of your HomeSeer system from the HomeSeer [Tools] -> [Setup] -> [General] -> [Backup Config] menu and post that zip file, along with your  config.json, to a dropbox or other share site and send me the link?  I'd like to see if I can reproduce your error so I can try and fix the code. Thanks.

**Comment by jezzaf** [comment]
hi, 

I'm not sure what I did (changed to my computer form laptop) but now my original config is working. loads all devices with no errors. 

thanks for the help

**Comment by jezzaf** [comment]
you wouldnt happen to know why im getting 

Nov 25 14:09:17 raspberrypi homebridge[310]: [2018-11-25 14:09:17] [HomeSeer] Error: connect ENETUNREACH 192.168.0.3:84 - Local (0.0.0.0:0)

when trying to run it as a service? 

thanks

**Comment by jvmahon** [comment]
Sorry, but I don't.  I think this is more likely an issue with the "homebridge" component than with the plugin itself. If you Google homebridge ENETUNREACH you'll find multiple people have similar problems. Maybe one of them has posted something that can help you. .
