### ISSUE TITLE
Battery not reporting percentages

### ISSUE THREAD

**Issue by RiggsUS** [jvmahon/homebridge-homeseer#68]
None of my devices are reporting correct battery life, the only way I know I need to charge them is when the don’t work. All my devices are AeoTec, on HS Pro3

**Comment by jvmahon** [comment]
Are they (1) reporting incorrectly to HomeSeer, or (2) does HomeSeer have the correct value and it is just not being reported to the iOS device.

If its #1, there's noting I know to do to fix that.
If its #2, let me know the types of devices and maybe I can look into it.

**Comment by jvmahon** [comment]
No further response from OP so closing comment.
