### ISSUE TITLE
Window Blinds (issue with config)

### ISSUE THREAD

**Issue by darrenmcuk** [jvmahon/homebridge-homeseer#69]
I have some Somfy Blinds which are connected through RFXCOM...through HS is all well. 

			   {
				"type": "WindowCovering",
				"name":"Porch Blind",
				"ref": 6150,
				"openValue": 119,
				"closedValue": 118
				 }

Is what I have set for

Reference ID | 6150
-- | --
Technology Address | O1
Status | 118 = Unknown
Value | 118 = "Down"
String |  
Supports Status | False
Dimmable | False
Interface | RFXCOM
Extra Data Store | 0 Named entries, 0 UnNamed entries.
Device Type Internal | Plug-In API, Type: Plug-In Type 79, SubType: 61490009A1
Device Type (String) |  
Misc Settings | Show Values, SET_DOES_NOT_CHANGE_LAST_CHANGE
Device Image File | images\Devices\Image-Not-Selected.png
Thumbnail Image File | images\Devices\Image-Not-Selected_small.png
Relationship Status | Not Set

Reference ID | 6150
-- | --
Technology Address | O1
Status | 119 = Unknown
Value | 119 = "Up"
String |  
Supports Status | False
Dimmable | False
Interface | RFXCOM
Extra Data Store | 0 Named entries, 0 UnNamed entries.
Device Type Internal | Plug-In API, Type: Plug-In Type 79, SubType: 61490009A1
Device Type (String) |  
Misc Settings | Show Values, SET_DOES_NOT_CHANGE_LAST_CHANGE
Device Image File | images\Devices\Image-Not-Selected.png
Thumbnail Image File | images\Devices\Image-Not-Selected_small.png
Relationship Status | Not Set

However, I seem to bet getting lots of 

** Warning - Possible Illegal value for window covering setting

errors...and the blinds don't seem to operate.

what am I doing wrong?

Thanks

Darren

**Comment by jvmahon** [comment]
I just checked and there's an error in the plugin which generates an error message if the values aren't in the range 0-99 or 255 (which are typical ZWave values). I'll try to patch it today or over the weekend.

**Comment by jvmahon** [comment]
I think it is now fixed. Please test and confirm. You can get the updated version by:

     npm -g update

For your Window covering, you'll need to indicate its a binary (open  / closed) device, rather than a percentage so add the binary flag to your accessory description like:

{

			"type": "WindowCovering",

			"name":"Porch Blind",

			"ref": 254,

			"openValue": 119,

			"closedValue": 118,

			"binarySwitch":true

			 }

**Comment by darrenmcuk** [comment]
Hi ya,

Not sure what I am doing wrong but...

** Warning - Possible Illegal value for window covering setting

Is my config:
			   {
				"type": "WindowCovering",
				"name":"Porch Blind",
				"ref": 6150,
				"openValue": 119,
				"closedValue": 118,
				"binarySwitch":true
				 }

As far as I can see everything seems to be upgraded:

+ homebridge-homeseer-plugin-2018@2.3.18
added 85 packages from 93 contributors in 48.813s

Thanks,
Darren

**Comment by jvmahon** [comment]
It looks like something went wrong and my code on GitHub didn't update correctly. I'll check into this again.

**Comment by darrenmcuk** [comment]
That did the trick. Many thanks for the excellent support.

**Comment by jvmahon** [comment]
You're welcome.
