### ISSUE TITLE
temperature and negative values

### ISSUE THREAD

**Issue by AlanSmithe** [jvmahon/homebridge-homeseer#7]
I noticed that the temperature sensors always display 0℃ in HomeKit applications when it's a negative temperature.

I found [this](https://github.com/KhaosT/HAP-NodeJS/issues/147) page on github that discusses the same issue.

> Application should override minValue if the value it tries to display is lower than default minValue. The current min/maxValue are generated from Apple's HomeKit Accessory Simulator.

Apparently this can be solved by 
`
characteristic.props.minValue = targetMinValue
`

Is there a way to implement this?

**Comment by jvmahon** [comment]
Done. New release 2.0.4 (also fixed problem error that occurred if the config.json file had no "Events" field.
Thanks for the feedback. Keep letting me know of issues that you find.
