### ISSUE TITLE
Request for parametrable Device name

### ISSUE THREAD

**Issue by goldriver2** [jvmahon/homebridge-homeseer#72]
Could the naming convention be a parameter in the config.json file ? 

It could be programmed so that anyway the user want it he could configure it, if a user want the room, the floor, the device name or the voice command he could activate a flag ?

I would like to have "Voice Command" description sent to Homekit rather than "Device Name" (refering to Homeseer "Voice Command" parameter in the homeseer devices). For me, I would also prefer if only "Voice Command" was sent without any reference to the room

Now, once I start Homekit, I have to go and manually modify all device names because they appear "Room.Device Name"

**Comment by goldriver2** [comment]
Ok Thanks for the input, Hope someone will grab the ball ...

**Comment by goldriver2** [comment]
I wastesting the "my custom name" wich did not work, looking in the wiki, I found that the parameter should be "name" which works fine for Lightbulb but if I use the "name" parameter for other Type of accessories ( I tried GarageDoorOpener and Thermostat) the name is not transmitted to Homekit, I still have the default name appearing in the Homekit

**Comment by jvmahon** [comment]
Sorry, I wrote that unclearly, I meant you should specify the naming parameter as ...

       "name":"Your_Name_Goes_here"

So for garage door openers, it would be something like ...

      {"type":"GarageDoorOpener", 		"name":"myGarageDoor", 	"ref":710, 	"obstructionRef":711 },

Is that what you did and it didn't work?  If that's the case, then this is a bug and I will try to fix this.
