### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by meluvalli** [jvmahon/homebridge-homeseer#73]
Latest version no longer works in windows.  Just says "Undefined"

1/7/2019, 1:45:15 AM] [HomeSeer] Initializing HomeSeer platform...
[1/7/2019, 1:45:15 AM] [HomeSeer] System default periodic polling rate set to: 10 seconds
Load homebridge-HomeSeerPlatform.HomeSeer
[1/7/2019, 1:45:16 AM] [HomeSeer] undefined

Last known version to work was 2.3.15. 

This started happening when I updated to 2.3.19.

Tried re-installing from scratch and same problem.

**Comment by jvmahon** [comment]
What platform are you using (linux or Windows).
I'm not sure why you are getting this error, but I'll try to help.  I've tested it with the latest node version (11.6) and it works fine for me.

Please start with some basics:
1. Check which version of node you are using and update to latest (11.6). See https://nodejs.org/en/
2. Uninstall the plugin then re-install:
        npm -g uninstall homebrige-homeseer-plugin-2018
        npm -g install homebridge-homeseer-plugin-2018

3. Do a full update of all your npm modules
        npm -g update
4. Try a simplified config.json - one with only a one or two accessories in it to see if it works.

If you still can't get it to work, please post a copy of your config.json file.

**Comment by meluvalli** [comment]
Ok.   Here is what I have tried:

I am runing node-v10.2.1-x64.   This is on Windows x64 System.

I tried completely uninstalling EVERYTHING.   Python, OpenSSL, Visual Studio Build Tools, and NPM.

I then went in and delete the following directories:
%UserProfile%\.config
%UserProfile%\.homebridge
%UserProfile%\.node-gyp
%UserProfile%\.windows-build-tools
%AppData%\npm
%AppData%\npm-cache

Removed all this hoping to start from scratch.

Re-installed as per direction on https://github.com/jvmahon/homebridge-homeseer/wiki/Windows-10-Installation.

Same issue.

Couple odd things...
#1. If I don't have a config file, it loads fine.   Granted I can't load any devices or anything, but at least it loads :)
#2. My config was working.  So, I am sure it's not messed up, but I took your recommendation and simplified the config.  So Below is my config:

`
{
    "bridge": {
        "username": "00:32:3D:E4:CE:04"
    },
    "platforms": [
        {
            "platform": "HomeSeer",
            "host": "http://127.0.0.1:8189"
        }
    ]
}
`


Basic as it gets!  HAHA :)  But same result.   I ended up creating a new machine and installing and everything works with the same versions of everything.   So, I am very lost as to what could be causing this :(...  I really wish I could figure it out though because I don't want to have to wipe the machine I was using originally..   If you have ANY recommendations, I would REALLY appreciate it!!!!

**Comment by meluvalli** [comment]
Ok.  Update again :)

After doing some googling, I was able to add the below line:
 "mdns": { "interface": "[My Internal IP]" },

This seems to have fixed the "Undefined" error!  So just left with the certificate question :)

**Comment by jvmahon** [comment]
Sorry, I've never seen an error caused by a certificate, so I may not be of much help.. I've been using node 11.6 and one suggestion I can make is to try that. Also, as to the config.json, I usually include a port, pin, the ASCIIport, ad at least one accessory as follows:

<pre><code>
{
	"bridge":
	{
		"name": "Test-Homebridge",
		"username": "CD:22:3D:E3:CE:41",
		"port": 51829,
		"pin": "032-45-155"
	},

	"description": "This is an test configuration file.",

	"platforms":
	[
	     {
			"platform": "HomeSeer",
			"name": "HomeSeer",
			"host": "http://192.168.0.2:80",
			"ASCIIport":11000,

			"accessories": [
							{
							   "type":"Lightbulb",
							   "name":"Ensuite",
							   "ref":833,
							   "onValue":100,
							   "offValue":0
							}
						]
		}
	  ]
}
</code></pre>

**Comment by meluvalli** [comment]
Bummer :(

I upgraded Node.js to 11.6...  I had to use "npm rebuild" command to get HomeBridge to work again.

But, still get certificate error :(

[1/9/2019, 2:29:10 AM] Loaded config.json with 0 accessories and 1 platforms.
[1/9/2019, 2:29:10 AM] ---
[1/9/2019, 2:29:10 AM] Loaded plugin: homebridge-homeseer-plugin-2018
homebridge API version: 2.2
[1/9/2019, 2:29:10 AM] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
[1/9/2019, 2:29:10 AM] ---
[1/9/2019, 2:29:10 AM] Loading 1 platforms...
[1/9/2019, 2:29:10 AM] [HomeSeer] Initializing HomeSeer platform...
[1/9/2019, 2:29:10 AM] [HomeSeer] System default periodic polling rate set to: 10 seconds
Load homebridge-HomeSeerPlatform.HomeSeer
[1/9/2019, 2:29:10 AM] [HomeSeer] Error: unable to verify the first certificate

**Comment by meluvalli** [comment]
Just an update in case anyone else runs into this problem with the certificate....

I found an article online where someone else had the same problem with a self-signed certificate...  Granted, I'm not using a self signed, but a Lets Encrypt...    I'm not sure why I would have the cert issue with Lets Encrypt.   I confirmed the certificate is valid and confirmed even Windows/Google Chrome see it as valid...

Anyhow, I edited the %AppData%\npm\node_modules\homebridge\bin\homebridge file and added the below line:

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

The file now looks like:

```
#!/usr/bin/env node

//
// This executable sets up the environment and runs the HomeBridge CLI.
//

'use strict';

process.title = 'homebridge';

// Find the HomeBridge lib
var path = require('path');
var fs = require('fs');
var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

// Run HomeBridge
require(lib + '/cli')();
```

**Comment by jvmahon** [comment]
Thanks. This then looks like more of a "homebridge" issue than an issue with any specific plugin. Consider posting something about this in homebridge section. See [https://www.npmjs.com/package/homebridge](url)

Thanks.
Jim
