### ISSUE TITLE
Fibaro RGB...how to expose

### ISSUE THREAD

**Issue by darrenmcuk** [jvmahon/homebridge-homeseer#75]
So I have a fibaro RGB controller all hooked up.....what's the best way to expose this to Homekit?
![rgb](https://user-images.githubusercontent.com/33957097/52911902-fdc23f00-32a1-11e9-8dfc-3f1489ed9ed0.jpg)

**Comment by jvmahon** [comment]
I haven't implemented any RGB support.
Given that, I think you could expose each RGB channel (Red, Green, Blue) as a separate dimmer device. You could then put them all on the same page on the iOS home app and name them Red, Green, Blue, etc. You could also create some virtual switch / dimmer devices in HomeSeer where adjustment of the devices trigger HomeSeer events to adjust the  Fibaro controller. You could then expose the device to  Homekit.  For example, you could implement an overall "brightness" control as a virtual dimmer which, if adjusted in HomeKit, would trigger an  HomeSeer event to adjust all the channels proportionally or some other thing like that.

**Comment by darrenmcuk** [comment]
Thanks for the ideas...
