### ISSUE TITLE
Generic status-only device that indicates on/off status

### ISSUE THREAD

**Issue by rrman** [jvmahon/homebridge-homeseer#76]
I have a need for a generic status-only device type that will indicate if the device is "On" or "Off", but does not allow the user to actually turn the device On or Off. Something like "GenericSensor". This type would only be for showing the status of a device from Homekit.

For example, I have a number of virtual devices defined in HomeSeer that are status-only which represent the status of some appliances. For example: Washing Machine (On or Off), Toaster Oven (On or Off) and Sump Pump (On or Off). Aside: I use the Zooz ZEN15 Power switch to keep track of these appliances' watt usage and based on the wattage as well appliance-specific behavior, I set the virtual device to On or Off to reflect if the appliance is being used or not. But, I don't want to give users the ability to turn them on or off from homekit (doesn't make sense to let user turn on a washing machine from the iPhone). Hence, I have a need for a generic status only device type in homekit/homebridge.

The issue I'm having is what type should I define these virtual device in Homebridge/Homekit? I'm not aware of any generic status-only homekit/homebridge that will just report the status. So, depending on the homekit/homebridge type that I use, other family members using a homekit app can get confused when using a homekit app. For now, I'm used one of the following types of HomeKit/homebridge types: 

- Washing Machine: I use MotionSensor type. Homekit says motion has been detected when the washing machine runs... not quite the desired message though. If I use the LeakSensor type, then Homekit will say that a leak has occurred whenever the washing machine runs, making thing more confusing. 

- Toaster Oven: I use SmokeSensor. The problem with this type is if the Toaster Oven is on, Homekit says that smoke has been detected. Not quite the right type. I can't use MotionSensor, because if the toaster oven is on, homekit says that motion has been detected. Not quite the right type either. ContactSensor, LightSensor, etc. don't make sense to use.

- Sump Pump On: I use LeakSensor. Better match than SmokeSensor and MotionSensor, I suppose. 

Anyway, for me, since I configured the json files, I know what these devices are supposed to represent. But for others (e.g. Wife), if they see "smoke has been detected' when the toaster oven is on, it can cause confusion/panic.

So, I'm wondering if there is a type like "GenericSensor" that can be used to just have Homekit show an on or off status (no control, just status), and will just say that the device is on in the status/notification messages??

Thanks.

**Comment by jvmahon** [comment]
I suppose you could simply expose the switches and then if they get turned on or off, trigger an event which re-checks whether they need to be reset.  This event would serve to intercept any manipulation from HomeKit.

For example, Let's  say the virtual device is Device1. Expose this to HomeKit using the standard way I've provided to create a switch in HomeKit.

In HomeSeer, create a event that triggers on any change in Device1.  When the event  changes, it  may be because of your Zooz watt sensing event causing Device1 to change, or it  may be because HomeKit sent a  change.   In either case,  the event should  "re-check" the device status by comparing it to your watt thresholds.  If the change resulted from  a Zooz- triggered change, the  event would essentially just confirm the setting already made so it doesn't need to do anything. However, if Device1 was changed because the user did a change from the Home  app, then when you re-check the watt levels, you can set the Device to what it should be an "undo" the user's change.

**Comment by rrman** [comment]
The disadvantage of exposing on/off switches is it gives users the false impression that they can actually turn on or off the appliance from Homekit, which either (1) doesn't make sense (e.g. turning on washing machine for example won't actually turn it on) or (2) on/off isn't something I would want the user to do remotely from an iPhone (e.g.  I don't want someone turning off the washing machine inadvertently while it is running). So, to me, using a not-so-accurate sensor type is better than an on/off switch whose buttons won't/shouldn't really do anything in response to user pressing on or off. 

Does homekit actually need very specific sensor types (like LeakSensor, MotionSensor, etc.) or does to have some support for a generic type of sensor that merely reports on/off without any implications of what it means (so Home App won't say leak detected or smoke detected, etc.)?

Thanks.

**Comment by jvmahon** [comment]
HomeKit does require you to be specific and there are a limited set of types you can choose from. I think the closest to a "generic" is the ContactSensor type.  In case you weren't aware, I believe that you can change the icon in the Contact Sensor's settings page in the Home app so maybe you could use a different icon to get a more sensible appearance.

I noticed you are using watt meters to determine if a device is  on/off. If you haven't already see  this wiki entry, it may be of interest to you:  [Energy Meters](https://github.com/jvmahon/homebridge-homeseer/wiki/Energy-Meters)

**Comment by rrman** [comment]
Thanks. I was afraid that would be a Homekit limitation. ContactSensor states are Open/Closed, so the states don't quite appropriate for reflecting the On/Off states of appliances.

Showing wattage use is interesting, and I may also show that in addition to using the On/Off virtual devices. However, the wattage can be deceiving for my uses. For example, when my toaster oven is on, it often goes down to 0 watts for a few seconds (I've observed it can go down to 0 watts for up to 55 seconds). So, I wait until it's been 0 watts for at least 90 seconds before turning off the toaster oven virtual device. Similar issue with the washing machine. It can use up to 5 watts at times when it is not being used, so I wait for it to exceed a minimum threshold before changing its virtual device to "On".

Thanks for your feedback!
