### ISSUE TITLE
authentication to the the homebridge-homeseer....

### ISSUE THREAD

**Issue by Bi7** [jvmahon/homebridge-homeseer#79]
Is is possible to add authentication to the the homebridge-homeseer connection to HomeSeer?

I played around with it like it was an http accessory adding username and password, but that did not work.  I have searched looking for this question but found nothing. I am using Windows 10 with node.js installed on the same machine as HomeSeer.

Thanks, this project is fantastic!

B

**Comment by jvmahon** [comment]
Sorry, I did not include username / password support. 

I'm guessing that adding it is a matter of modifying the code at about lines 328-347 of Index.js (where the ASCII connection is made) as well as code wherever there is a promiseHTTP function (index.js and others). As a practical matter, I don't expect to do any significant work on this until Apple does its next significant update to homekit (I'm guessing that will be some time after iOS 13), but if someone else took the lead and submitted a pull request, I would consider integrating changes.
