### ISSUE TITLE
Virtual Devices

### ISSUE THREAD

**Issue by mugen5** [jvmahon/homebridge-homeseer#80]
I created a virtual homeseer device that would control and event to open/close blind as explained in the wiki. When I try to open the blinds with homekit i get "JSON controldevicebyvalue ref 774 value not found " in the log. Virtual device 774 is set to 0 for off and 255 on. Configuration in .json file is below. Closing it works fine. Any idea what I'm doing wrong? 

	"type": "WindowCovering",
	"name": "Bedroom Blind",
	"ref": 774,
	"uuid_base": 0,
	"batteryRef": 0,
	"batteryThreshold": 25,
	"openValue": 255,		
	"closedValue": 0,		
	"binarySwitch":false,   
	"obstructionRef":0,		
	"obstructionClearValues":[0]

**Comment by jvmahon** [comment]
I don't know but will try to help.
Can you post a copy of the corresponding HomeSeer device(s) and the events you are using?
What platform are you on (Windows 10, Raspberry, ??).
Thanks
Jim

**Comment by mugen5** [comment]
Windows 10. Yes value was changed to 255. 

![Untitled](https://user-images.githubusercontent.com/38895015/59634212-9c618e00-9124-11e9-9615-4c585021bcbf.jpg)
![Untitled1](https://user-images.githubusercontent.com/38895015/59634227-a71c2300-9124-11e9-9740-28de7930122a.jpg)
![Untitled2](https://user-images.githubusercontent.com/38895015/59634240-ad120400-9124-11e9-9da4-32d538260670.jpg)

**Comment by jvmahon** [comment]
I noticed you had "binarySwitch" set to false -- it should be True in this case since your switch is only 2-state. Also, uuid_base should generally be the same as the Ref. If you don't specify it, it will be automatically set so leave that out. I'd simply try simplifying your config.Json by setting only the following parameters for your blinds as the remaining values should be automatically set to proper defaults (hopefully). Give this a try and let me know if you have better luck (or get a different error).
If this doesn't work, the next step is for me to try and re-create a virtual blind and test it out a bit, but I won't be able to do that until the weekend.

{ "type": "WindowCovering",   "name": "Bedroom Blind",  "ref": 774  }

**Comment by mugen5** [comment]
I tried simplifying .json file and get the same error. I have like 20 different virtual switches that homekit controls and they all work. Not sure why this one doesn't. Strange thing is all the others are set to "100" for on and not "255". I may just try to re create another virtual one to see what happens. Might not have time tonight. Will let you know once I have tried a new one.

**Comment by jvmahon** [comment]
Yeah, I think that's the way to go.
I'd suggest you create a new Virtual Device and then, at first, don't associate it with any events. Rather, first set it up with Homebridge and see that it appears on your iPhone and can be turned on / off. After that, create your events.

**Comment by mugen5** [comment]
I deleted all the events, virtual device and everything in the .json file related to this. I created a new virtual device and making sure on was at 255. Mapped it true homebridge and still getting the same error. I tried this with garage door opener and it works fine. FYI I have ordered Z-wave blind motors true indiegogo and they are supposed to start shipping at the end of the month so I may not need this for long. Don't spend to much time on this but if you do stumble unto something do let me know. Thanks.

**Comment by jvmahon** [comment]
The fact that garage doors open but windows don't is a great hint as the code should be very similar. I'll check the WindowCovering code for a bug.

But before I check, can you try resetting your virtual device so that 99 is the "on" value, and then set "openValue:99" in your config.json and let me know what happens.

**Comment by jvmahon** [comment]
Are you using the latest version of the plugin?
to be sure, from a command window, execute:

     npm -g update

I tried to re-create the problem on my own system, and everything works fine.

My virtual device was #1121 and my config.json included the following entry:

	  	{"type": "WindowCovering", "ref":1121, "binarySwitch":true, "openValue":100, "closedValue":0}

**Comment by mugen5** [comment]
Updated and everything works. I re did my events and can control blind from Homekit and when open with switch it updates Homekit device. I do have one small issue. The virtual switch is called "bedroom blind" however in HomeKit it appears as "Homekit.bedroom Blind" I added ""name": "Bedroom Blind", to the code however still appearing as Homekit.bedroom blind.

**Comment by jvmahon** [comment]
Glad to hear it is working.

I'll check on the naming issue. However, there is an easy fix - you can just change the name from within the iPhone's Home application. When you rename the device in the iPhone home application, the "new" name will "stick" even if you reboot  / restart Homebridge. Basically, homebrige will permanently use whatever was the last name entered in the iPhone's Home app.

**Comment by mugen5** [comment]
Ok thanks for your help. Renaming did work. Just hope I don't have to rename everything I add in the future. So if it's in fact the update that fixed my issue is this something I need to do periodically. Does it not update automatically.

**Comment by jvmahon** [comment]
Unfortunately, updating of the plugin does not occur automatically. Updating is controlled by node package manager (npm) and I'm not aware of any ability to have it automatically check (other than entering the "npm -g update"). I suppose you could use Windows Task Scheduler to run a command to execute npm -g update, but I haven't tested it out. Usually what I do is I update node itself every few releases and then do a npm -g update on the node files.

As for renaming everything in the future, what I usually do is I don't put the names in the config.json file. I just let the plugin auto-name them and then I rename in the iPhone Home app.   So I do end up renaming everything, but it doesn't seem (to me) to be much more work than if I had inserted all the names in the config.json in the first place. Basically, its an "enter here or enter there but you still have to enter it somewhere" type of choice.
