### ISSUE TITLE
How to run on windows startup ( New method )

### ISSUE THREAD

**Issue by rmohsenn** [jvmahon/homebridge-homeseer#81]
Hello

I just installed Homebridge on windows 10 using the new method and I can't figure out how to run it on windows startup , tried everything , batch file to open an new cmd window and type " Homebridge " It didn't work either .

sorry if this is not an issue but I don't know where to ask for this 

Thanks
Rami

**Comment by jvmahon** [comment]
See Wiki page which explains how to start HomeSeer and HomeBridge using Windows Task Scheduler.

**Comment by rmohsenn** [comment]
i did , for HS3 it was referring to the HS3.EXE file , but for homebridge i don't think it will be the same way

**Comment by rmohsenn** [comment]
I completely failed to mention that I’m on Windows 8.1

**Comment by rmohsenn** [comment]
I figured it out. I found the shortcut in the npm folder. Thank you

**Comment by jvmahon** [comment]
I'll add some more info to the Wiki to help the next person, but to be clear, what is done is in the task scheduler, you set up a task that runs the command line. I.e., the "Action" is to run the following Program/Script:

     c:\windows\system32\cmd.exe

This simply runs an "ordinary" command window. You get it to run "homebridge" via the specific arguments you set for that action. Specifically, in the "Add arguments (optional):" settings box for the Action, you insert the argument to actually run homebridge which will look like this:

       /C "C:\Users\HomeSeer User\AppData\Roaming\npm\homebridge -U c:\users\HomeSeer User\homebridge"

This assumes that the auto-logged-in user is named "HomeSeer User" as explained in the Wiki, else change that part of the path to the user's name. The first part of this command line ("C:\Users\HomeSeer User\AppData\Roaming\npm\homebridge")  is where you find the shortcut to start homebridge. The second part of this command line ("-U c:\users\HomeSeer User\homebridge") tells HomeBridge where to find its config.json file.

In the image below, you obviously can't see the full Arguments box content, but it should be what I indicated above

<img width="340" alt="Action Pane Capture" src="https://user-images.githubusercontent.com/15061942/59975951-570de800-958c-11e9-98eb-fe81d772c7e2.PNG">

**Comment by rmohsenn** [comment]
Thanks again. I found a simpler easier solution for both HomeSeer and Homebridge. I use startup delayer software. I added both HS3 exe and homebridge shortcut ( found it in the NPM folder in Roaming user folder ) and its working perfectly
