### ISSUE TITLE
GarageDoorOpener

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/homebridge-homeseer#83]
Anyway to include the old plugin way of working garage door openers (i.e. controlRef and stateRef)? I have a garage door opener and a separate contact sensor. I'd like the contact sensor to be able to be forwarded to iOS as part of the door opener. Thanks! I tried running both the old and new Homebridge Homeseer plugins at the same time but get this error: Error: The requested platform 'HomeSeer' has been registered multiple times. Please be more specific by writing one of: homebridge-homeseer.HomeSeer, homebridge-HomeSeerPlatform.HomeSeer

**Comment by jvmahon** [comment]
Can you show / explain how the garage door opener works in HomeSeer - i.e., are there any "events" you currently use to control it? How is the HomeSeer device set up. Screen shots would be very helpful. Thanks.

**Comment by jvmahon** [comment]
I"ve added some updates to the "Wiki" page to show how this would work using a "virtual" garage door and some very simple events. I'll fill this out in the coming week with some additional details on the events which will also give the "nicer" HomeKit animation of the door opening / closing.
