### ISSUE TITLE
HomeSeer HS-FC200+ Fan Controller Speeds Support

### ISSUE THREAD

**Issue by nphil** [jvmahon/homebridge-homeseer#86]
Hello,

I've been setting this up by slowly exposing some of my HomeSeer devices to HomeKit. I had previously had all my Z-Wave devices on Hubitat and used a similar bridge.

This fan controller's status page looks like [this](https://imgur.com/a/QonWI9Q).

There are 4 values - 0, 24, 49,74 and 99 for the different speeds. The issue is that setting any value from homekit other than these specific values will not do anything to change the speeds on the fan. On/Off still works. This is the relevant JSON section:

`{
                    "type": "Fan",
                    "ref": 7,
                    "can_dim": true,
                    "uses99Percent": true,
                    "onValue": 99,
                    "offValue": 0
                },`

Is there any workaround that does not involve event programming from HomeSeer to get around this? I'm still new to HomeSeer so any help is appreciated!

**Comment by jvmahon** [comment]
There are several ways that you may be able to do this . . .

I haven't tried this before as I don't have a fan controller, but one possible solution:
You'll need to alter  your fan controller "Status Graphics" page to delete the 24, 49, 74, 99 and make it look more like a Dimmer's Status Graphics page as shown below. Make sure you save a screen shot of your original Status Graphics page so you can go back to it if it doesn't work.

I believe what *should* happen is that if the device is sent an intermediate value, say 20, it will "map" it to one of the expected values, say 24, and then report "24" back to HomeSeer. A disadvantage here is that you do lose the simple 0, 1, 2, 3, 4 push-button interface on HomeSeer and, instead, get a dimmer-like slider.


![image](https://user-images.githubusercontent.com/15061942/65501379-e928d380-de8e-11e9-8985-e3c2e0160098.png)

**Comment by jvmahon** [comment]
Or . . .
Do you have the "Easy Trigger" plugin. It is well worth the money -- particularly as you're new to HomeSeer, this is very helpful for writing more complex events. If you have that plugin, I could show you what to do using some simple events and a virtual device dimmer.

**Comment by pdonlin** [comment]
I was able to get this working by configuring my status text and graphics as follows. The homebridge config is setup like a dimmer. The switch itself will still use the set intervals so I wanted to keep the default graphics settings and added the dimmer slider. 

![2C383CC0-5C34-4329-81A0-FCE2E78DD596](https://user-images.githubusercontent.com/8090246/65503615-4757b580-de93-11e9-8e56-812492392d51.jpeg)
![B7B649F7-13DC-475C-8106-CE2F00215FFC](https://user-images.githubusercontent.com/8090246/65503616-4757b580-de93-11e9-84da-232833000ea0.jpeg)

**Comment by jvmahon** [comment]
@pdonlin - Thanks for the tip. I'll add that to the Wiki.

If you were to select an intermediate value on HomeKit or using the slider, say 30, does the Fan Controller then "adjust" that value to one it would expect and send back that response, or does it stay at the 30 value?

**Comment by pdonlin** [comment]
It stays at the set value. The fan controller does not increase speed (or light up the proper switch status lights) until you pass the set thresholds. For a 3 speed fan that means the actual setting ranges are:
1-33 speed 1
34-66 speed 2
67-99 speed 3

It functions like the GE fan switches when controlled via HomeSeer or HomeKit.

**Comment by jvmahon** [comment]
O.K., so for a 3-speed, if you set it to, say 30, the fan would turn on as if it were set to 33, but the indicator light on the HomeSeer switch would not turn on a level 1? 

Obviously, that isn't what a user would want, but I might be able to add something to my HomeKit code to fix this.

**Comment by pdonlin** [comment]
Sorry I could have been clearer. When set anywhere in the defined range the proper indicator lights up. The switch will not increase from speed 1 to 2 until you get to 34.

**Comment by jvmahon** [comment]
@pdonlin. Thanks. 
Could you also provide your status graphics pages as ".png" files using the Windows Snip tool?  *.jpg files can't be used on the wiki pages.

**Comment by pdonlin** [comment]
Sure I’m on my phone so I had to resort to a quick screenshot. I’ll take better captures later and upload.

**Comment by pdonlin** [comment]
Attached are new PNG screenshots. Also here is how I setup the config.json for the device.

`{
  "ref": xxxx,
  "type": "Fan",
  "name": "Ceiling Fan",
  "offValue": "0",
  "onValue": "255",
  "can_dim": true,
  "uses99Percent":true,
  "uuid_base": "xxxx"
},`

![FC-200_Status-Text_3-Speed](https://user-images.githubusercontent.com/8090246/65546089-c32e1e00-dee4-11e9-9ffa-51396a318ff0.png)
![FC-200_Status-Graphics_3-Speed](https://user-images.githubusercontent.com/8090246/65546162-ef499f00-dee4-11e9-9b95-90b16c156302.png)

**Comment by jvmahon** [comment]
Thank you.

**Comment by nphil** [comment]
This works great, thank you!

However - it breaks Alexa functionality. The device shows up as a dimmable light in Alexa, which is fine, but it's stuck "waiting for HomeSeer" forever.

I even tried deleting, enabling and disabling voice and re-adding to alexa - same result.

**Comment by jvmahon** [comment]
One solution I can think of is:

 1) creating a virtual dimmer device which you then link to HomeKit as a Fan device
2) Continue using the "real" HomeSeer fan controller device, with its 4 levels, to link to Alexa
3) Create a series of events linking changes to the virtual dimmer to the "real" device and vice-versa such that, when the virtual dimmer is changed, you trigger a corresponding change to the "real" fan controller and vice versa. For example, this would include a series of events like ... 

if virtual dimmer set in range 0, then set real fan controller to Off; 

if virtual dimmer set in range 1-24, then set real fan controller to level 1; 

if virtual dimmer set in range 25-49, then set real fan controller to level 2;

etc.

and corresponding ones like:
if "real" fan controller set to Level 0, then set virtual dimmer to 0.
if "real" fan controller set to Level 1, then set virtual dimmer to 24.
if "real" fan controller set to Level 2, then set virtual dimmer to 49.
etc.

These events are probably easier to write using the Easy Trigger plugin as it works better for triggering on a device change and then checking the range of the new value.

**Comment by jvmahon** [comment]
Also, as you may know, HomeSeer Version 4 is supposed to be released in the November timeframe. At that time, I'll likely update the plugin and will include some better handling of the fan controller. This may involve me including an additional "Fan" type (e.g., "FanV2" in which you can map ranges of values to the various HS Fan controller levels). I f I can get a HS Fan controller to test this on, I might add that before then.
