### ISSUE TITLE
Can't open blinds

### ISSUE THREAD

**Issue by mugen5** [jvmahon/homebridge-homeseer#87]
As you may remember I posted about an issue back in June were I couldn't control my blinds true a virtual device. After doing the update it started working. I recently changed the motors and are now Z-wave tilt motors that I can control directly with HS so redoing HomeBridge codes to open the z-wave motors but I'm having the same issue. I can close the blinds but when I try to open them I get "JSON controldevicebyvalue ref 774 value not found " in the log. I have tried with multiple motors and have the same issue. Below is what I have in the .json file. And yes the devices open value is 255 I checked. Tried changing to 100 in the .json files and in the device with same result. Strange thing is if I change type from "WindowCovering" to "GarageDoorOpener" it works as it should so coding and devices appears to be ok. I tried doing an update again but still no luck. Any ideas of why this is not working? Anything else I can try? 

"type": "WindowCovering", 
                                "ref":969, 
                                "name":null, 
                                 "openValue":255, 
                                 "closedValue":0}

**Comment by jvmahon** [comment]
Can you please let me know what tilt motors you are using and post an image of your "Status Graphics" page for those motors. Thanks.

Its very odd that you are getting a "controldevicebyvalue ref 774" error as your Config.Json is set to a ref of 969. Are there any other messages you see on the screen before this error? Usually the plugin will indicate the ref. to which it is transmitting and the transmit values.

**Comment by mugen5** [comment]
I pasted the wrong log file message. This is the one "JSON controldevicebyvalue ref 969 value not found" from a few minutes ago. I'm using Iblinds. See below screenshot. 

![Screenshot](https://user-images.githubusercontent.com/38895015/66436239-ec7a9e00-e9fc-11e9-9fb4-72b7b315ee76.jpg)

**Comment by jvmahon** [comment]
Homekit expects Window Coverings to be a mutli-level device, i.e., that you can open/close them to any level from 0 to 100%, while your devices are binary.  To handle this, change your config.json settings to include "binarySwitch":true and let me know if that works. See below.

{"type": "WindowCovering",
"ref":969,
"binarySwitch":true,
"name":null,
"openValue":255,
"closedValue":0}

**Comment by mugen5** [comment]
It worked. thank you.

**Comment by jvmahon** [comment]
You're welcome.
