### ISSUE TITLE
Cannot control Schlage Z-Wave Lock

### ISSUE THREAD

**Issue by leonmich** [jvmahon/homebridge-homeseer#88]
For some reason I'm unable to control a Schlage Z-Wave Lock. In iOS the lock shows up as 'Unlocked' and when I click it, it gets stuck on 'Locking' and nothing ever happens.  You'll see the error I receive 'JSON controldevicebyvalue ref 96 value not found'. 

Attached are homebridge config, homebridge log show device added, homebridge log showing attempt to 'lock' door, HomeSeer device config, HomeSeer ref 96 (root lock device) adv page, HomeSeer ref 99 (child 'door lock' device) adv and status graphics.   

Please let me know what else I can provide.

![lock-homeBridgeConfig](https://user-images.githubusercontent.com/35269273/67152826-bb228d80-f29a-11e9-8cc6-868f4b7fb26c.PNG)

![lock-homebridgeLog](https://user-images.githubusercontent.com/35269273/67152827-bbbb2400-f29a-11e9-9137-dc13e2889ab3.PNG)

![lock-homebridgeLog02](https://user-images.githubusercontent.com/35269273/67152828-bbbb2400-f29a-11e9-830b-49d40bfd416f.PNG)

![lock-homeseerLog](https://user-images.githubusercontent.com/35269273/67152861-86630600-f29b-11e9-871b-1255c7640e58.PNG)

![lock-homeseer01](https://user-images.githubusercontent.com/35269273/67152832-d68d9880-f29a-11e9-8ece-bc908d5e5c52.PNG)

![lock-ref96adv](https://user-images.githubusercontent.com/35269273/67152852-5582d100-f29b-11e9-98d4-264325c015a1.PNG)

![lock-ref99adv](https://user-images.githubusercontent.com/35269273/67152853-5582d100-f29b-11e9-97ec-425a9479df15.PNG)

![lock-ref99statusgraphic](https://user-images.githubusercontent.com/35269273/67152854-5582d100-f29b-11e9-8837-87c1b180efb6.PNG)

**Comment by jvmahon** [comment]
You have "ref" set to the wrong device. It should be set to the lock device, 99, not the root device, 96.  

I'm planning to do an update to the plugin once HomeSeer 4 is released and, in that update, plan to simplify the setting of config.json values (with the goal that the plugin will be better able to identify the correct reference values and select them automatically).

**Comment by leonmich** [comment]
Ugh, I feel like an idiot.  I swear I added 99 at one point but I probably didn't notice it in the Home App.  Most of the other devices I'm adding the root device.  Thank you for responding.

**Comment by jvmahon** [comment]
Can you double-check your statement that "Most of the other devices I'm adding the root device."  What type of devices are you using the root?

Maybe I"m forgetting something I put in the code to traverse the root structure, but my recollection is I set up the plugin so you never use the root device as a reference.

More specifically, if HomeSeer shows a Z-Wave device as a Root plus controllable sub-devices, you should always be adding the reference for the controllable sub-device. For example, if you have a Z-Wave Plus dimmer that has a central scene function, Homeseer will show it as (i) a root device; (ii) a central scene device; and (iii) a dimmer device. In this case, its the reference of part (iii) (the dimmer device) that gets used  as the "ref" value for a "LightBulb" type device.

**Comment by leonmich** [comment]
Fibaro leak sensor is one that comes off the top of my head.  If there were a temp field I could reference as a child device similar to battery and tamper I would have the 'all in one'.  In the attached example I added the root 139.
![leak-homeBridge-fibaro](https://user-images.githubusercontent.com/35269273/67163587-f0c48680-f32d-11e9-999e-c8f96ec46407.PNG)
![leak-homeSeer-fibaro](https://user-images.githubusercontent.com/35269273/67163588-f0c48680-f32d-11e9-8f94-15b8aafec58f.PNG)

**Comment by jvmahon** [comment]
I don't think that works for a leak sensor - you need to set the "ref" to the device that changes when the sensor gets wet. To confirm functioning, wet your leak sensor and see if it is detected on your iPhone / iOS device - I believe you should have set the "ref" for the leak sensor to 145 for your fibaro sensor (or maybe 144 or 142).

Root devices don't change and don't report anything. You should look at HomeSeer while wetting the sensor to see which of the HomeSeer devices is being used to report the alarm condition. For sensors, is critical to always test and verify just to be sure.

**Comment by jvmahon** [comment]
I added a brief note on this point to the instructions in the Wiki. See section "B", here: https://github.com/jvmahon/homebridge-homeseer/wiki/Setting-Up-Your-Config.json-file

**Comment by jvmahon** [comment]
Also, FYI, you generally don't need to add the "batteryRef" or "batteryThreshold" values. There was a time when these had to be specified, but in one of the updates, I added code to auto-detect the batteryRef and there is a default batteryThreshold of 25. So unless you are using a very old version of the plugin, you don't need to specify these (though you can still use batteryThreshold if you want a value other than 25).

**Comment by jvmahon** [comment]
Finally, you can still set up / use the Temperature device using its reference 146. It will appear as a separate Temperature sensor within HomeKit.

**Comment by leonmich** [comment]
I appreciate you taking the time on a Sunday to respond.  All of this information has been extremely helpful in making this transition much easier.  Being able to get these sensors functional within HomeKit has reinforced the decision I made to move from Vera to HomeSeer. 

Also, in my case of the fibaro sensor [I found others](https://forums.homeseer.com/forum/homeseer-products-services/general-discussion-area/97632-fibaro-flood-sensor-z-wave-error-and-issues) who were trying to figure out what the various notifications were that the sensor was displaying.

Thanks again for the help and clarification!

**Comment by jvmahon** [comment]
I can tell you that I had such problems with my Fibaro flood sensors, that I switched to using HomeSeer sensors. That was a while ago and maybe the HomeSeer plugin has been updated and now works better. Good luck with yours. 

Also, if you're a new user, I strongly recommend the "Easy Trigger" plugin as a great tool for helping to write more sophisticated events as it lets you create "groups" of devices and control them as groups as well as trigger when any one of a group of devices changes. For example, you can define a group as all light devices located outdoors and then turn them on / off as a group. Its well worth the money.
