### ISSUE TITLE
Issue with GarageDoorOpener

### ISSUE THREAD

**Issue by kazibole** [jvmahon/homebridge-homeseer#89]
I updated my plugin to version 2.3.25 and found that my garage door opener virtual device was no longer working correctly in the Home app. I do not remember exactly which version I was running previously, I believe it was 3-5 minor versions behind.

I have instant status enabled.

Open (255) and closed (0) seem to work.

When I set the virtual device to opening (254), the Home app shows "closing..." and the log shows:
`ERROR - Unexpected Lock Target State Value of 254 for device 1269`

When I set the virtual device to closing (252), the Home app does show "closing..." but the log shows:
`ERROR - Unexpected Lock Target State Value of 252 for device 1269`

When I set the virtual device to stopped (253), the Home app shows "open" and the log shows:
`ERROR - Unexpected Lock Target State Value of 253 for device 1269`

Please let me know if you need more information or if I should try anything on my end.

Below is my configuration:

```
{
  "type":"GarageDoorOpener",
  "ref":1269,
  "openValue":255,
  "closedValue":0
}
```

I have also tried with:

```
{
  "type":"GarageDoorOpener",
  "ref":1269
}
```

And on startup the log shows the following:

`[HomeSeer] Config.json property information updated from: {"type":"GarageDoorOpener","ref":1269,"openValue":255,"closedValue":0} to: {"type":"GarageDoorOpener","ref":1269,"openValue":255,"closedValue":0,"name":"Homebridge.Status Garage Door","uuid_base":"Ref1269","obstructionClearValues":[0,74],"openingValue":254,"closingValue":252,"stoppedValue":253}`

**Comment by jvmahon** [comment]
Can you post an image of the "Status Graphics" page for the opener. I need to try and recreate the error.

**Comment by jvmahon** [comment]
I think what's going on is that my code does not expect a user to try and "set" the Garage door     to an intermediate state - it only expects you to attempt an Open or Closed.  So when you click on one of these intermediate states (i.e., "Opening", "Closing") the code sends an indicator to set the door's target to that state - but Opening / Closing aren't appropriate targets (they are valid for "current" state, but not "target"). I expect to rework the plugin a bit for HS4 so this fix may have to wait until then.

**Comment by kazibole** [comment]
Thanks for looking into it. It is not the end of the world so waiting for HS4 is fine.

**Comment by jvmahon** [comment]
I've not put this plugin in end-of-life stage. There is an updated plugin now in beta testing (homebridge-homeseer4) .  If this remains an issue, please post it there after installing / testing the updated plugin.
