### ISSUE TITLE
doorSensorRef prevents startup of homebridge plug-in

### ISSUE THREAD

**Issue by rrman** [jvmahon/homebridge-homeseer#91]
I long time ago, when I added my locks and deadbolts to config.json, I included "doorSensorRef" for each lock/deadbolt.

The plug-in's config.json documentations says that doorSensorRef is not currently used, but may be used in the future. I included "doorSensorRef" to all my locks and deadbolts if/when it is supported.

I just updated to the latest plug-in (as of 12/12/2019) using "sudo npm -g update".

Now, my homebridge won't start. I got the following error, and then homebridge exits:

Dec 12 10:28:01 homebridge homebridge[1825]: config.json error: property: doorSensorRef is not a valid property for item named: Garage Deadbolt of type: Lock.

I removed all doorSensorRef's from my config.json, and now Homebridge starts up okay.

I know doorSensorRef never did anything before, but was just there as a placeholder. Should homebridge not exit when it runs into doorSensorRef. Or, change the documentation to remove doorSensorRef.

Regards,

Randy

**Comment by jvmahon** [comment]
I'll take a look at this out over the weekend. I may just pull this out as it isn't used.

**Comment by rrman** [comment]
If it's pulled, just update the documentation to remove references to doorSensorRef.

Thanks,

Randy

**Comment by jvmahon** [comment]
This has been fixed. Do a npm -g update to get the update

Also, note there is a rewritten version of the plugin now available for beta testing. There are some minor changes needed to the config.json file (you need to add your login / password), and a few config.json parameters are no longer needed. If you're interested in testing, the updated plugin is "Homebridge-HomeSeer4" (though HomeSeer 4 is referenced, it does still work for HomeSeer 3). See https://github.com/jvmahon/Homebridge-HomeSeer4
