### ISSUE TITLE
Not technically an issue, but a pain point

### ISSUE THREAD

**Issue by NorthernMan54** [jvmahon/homebridge-homeseer#93]
I'm looking into an issue with my Homebridge-alexa plugin reported by users of the plugin

https://github.com/NorthernMan54/homebridge-alexa/issues/274

https://github.com/NorthernMan54/homebridge-alexa/issues/279

And after looking into the issue, found that the displayName/description field is using a weird value that isn't normal for homebridge plugins ( this is not part of the HAP spec from apple ).

It looks like this

https://github.com/jvmahon/homebridge-homeseer/blob/f7378a69b2734d151526cc78c5991b80519ef3c0/lib/HomeKitDeviceSetup.js#L228

Any reason you are setting these?

**Comment by jvmahon** [comment]
Yes, they have a purpose and you're correct, .displayName isn't part of the spec but I am not using it for "HomeKit" purposes - I'm really just carrying this data along with the actual HomeKit JSON data so I can print it for debugging purposes. Homebridge / HomeKit should just be ignoring this extra JSON data. Similarly, the string "Characteristic.TargetHeatingCoolingState"; is being used for its HomeKit purpose, its just a string that I sometimes output on console.log for debugging purposes - i.e., I could have just as easily set it to any other word or phrase.

**Comment by NorthernMan54** [comment]
And I used the same field, expecting the standard homebridge values for the field in my device characteristic parser in my Alexa plugin and my node-red module ( Homebridge-automation ).

Not a big deal, I just need to be aware of the issue and migrate away from the assumption that this field is not standard.

Tks

Have a Merry Christmas

**Comment by jvmahon** [comment]
Thanks! Good luck.

**Comment by jvmahon** [comment]
As a further comment, I don't really make much use of the .displayName variable anymore and if it is really causing problems, I could strip it out of my plugin. Let me know.

**Comment by NorthernMan54** [comment]
If you could, it would save me refactoring my device parser in the short term. I could then ask the users to update, and they will be happy

**Comment by jvmahon** [comment]
O.K., I published a new version of the plugin (2.4.2) - I think I have them all removed.

If you're asking users to update, you can also suggest that your users transition to my updated plugin, homebridge-homeseer4  (it still works with HS3 and requires less network resources so it should perform better).

Let me know if there is anything else I can do to help.

**Comment by NorthernMan54** [comment]
Thank you sir, much appreciated
