### ISSUE TITLE
HomeBridge crashing regularly on Windows 10

### ISSUE THREAD

**Issue by TURSTY** [jvmahon/homebridge-homeseer#94]
Hey, I have been using homebridge for a few years now on a windows 10 PC (I followed the instructions on this page to set this up), and have been frustrated with a issue for some time now. The Homebridge runs fine whether triggered manually via cmd, or run as a batch, but it will religiously crash out at least once a day with no apparent reason. I have tried to find any log that shows when its crashing to try and get an idea around timing, but have not been able to find anything. 

If I either re-run the batch or type homebridge into CMD it will restart and run with no problems, but inevitably disappear within a day again.

I have tried to work around this by running all sorts of scheduled tasks to restart homebridge several times a day, but even these have started to fail (I believe Windows has made some change to scheduled tasks and now I cant even edit them).

My HomeSeer app runs flawlessly on this machine with no issues, so its not the whole PC playing up.

Is this behavior you have seen before, or could you possibly offer some fault finding solutions?

If I cant get this sorted, I will just give up on the windows PC and run homebridge on a RasPi, but I would rather not have another device to worry about if I dont need to.

Cheers for a great product otherwise. 
Sam

**Comment by jvmahon** [comment]
I closed that by mistake.

I find homebridge to be very reliable on my Windows 10 PC.  Which version of Windows are you using?

There is an updated version of the HomeSeer plugin called homebridge-homeseer4 on npmjs which I just rolled out. Its github location is: https://github.com/jvmahon/Homebridge-HomeSeer4

My suggestion is to give that a try and also be sure to upgrade to recent versions of nodejs and homebridge.  I suggest using nodejs 13.5 (which is what I'm testing the plugin on).

Also, you don't say - but is the Homeseer plugin the only plugin or are you using multiple plugins? IF multiple plugins, what else are you using?

If you are using multiple plugins, you may want to separate them into separate instances of homebridge. There are instructions in the Wiki on how to do this.

**Comment by jvmahon** [comment]
Also, to start homeseer and homebridge, are you using the method I've outlined here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Automatically-Start-HomeSeer-and-Homebridge-at-Windows-Startup

**Comment by TURSTY** [comment]
Hey thanks for the quick response. 
I took a look at the versions I was running and its all really old (nodejs was 10.15.1). I was also running the sensibo sky plugin and the Camera ffmpeg plugin. 

I have wiped everything and started fresh with nodejs 13.5 and the new HB HS4 plugin and its all up and running again (although still on a single instance of homebridge). Will see how it goes stability wise after a day or two and let you know how I get on. Hopefully its was just a issue with 10.15.1 or something easy.

**Comment by jvmahon** [comment]
My strongest recommendation is to separate Sensibo Sky and ffmpeg into a different homebridge instances from the homebridge-homeseer4 plugin. I suspect they could be the problem; particularly ffmpeg - I could never get that to work properly myself. At least then if homebridge crashes you'll be able to diagnose which plugin was the problem. I think nodejs is less likely to be the issue. If you don't separate them at this time, I'd at least check that you are using recent ffmpeg and sensibo builds.

Its easy to separate the plugins. See the instructions here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Running-Multiple-Instances-of-HomeBridge
